BaSP-TG-45: timeSheets-entity-mateo
BaSP-a2022/ayom-a-trackgenix-app pull request #1
Opened 2022-10-31 20:24 UTC by matescarabino

- create list timeSheets with his update and delete buttons
- create a form to add new timeSheet and to update the previously listed ones
- add modals to show errors and double check on the delete function

2022-11-01 03:53 UTC, Ansitox reviewed
Just saw a wrong path on the layout, everything else looks fine

2022-11-01 13:45 UTC, ignacioaristo commented on src/Components/Layout/index.js
> +      currentScreen = <TimeSheetsFrom />;
Done.

2022-11-01 13:47 UTC, ignacioaristo commented on src/Components/TimeSheets/Form/index.js
> +        console.error(error);
Remove this console.log

2022-11-01 14:31 UTC, nicolasblasco submitted a review, later dismissed

2022-11-01 14:31 UTC, nicolasblasco commented on src/Components/TimeSheets/index.js
> +    saveList([...timeSheet.filter((timeSheet) => timeSheet._id !== id)]);
We are filtering the list by the deleted timesheet, what if the request fails? The timesheet won't be deleted from the database but the view will have a list without that timesheet.

2022-11-01 14:31 UTC, nicolasblasco commented on src/Components/Layout/index.js
> +    case '/time-sheets/form':
Timesheet is written together. So the route should be named /timesheets/form

2022-11-01 14:31 UTC, nicolasblasco commented on src/Components/Layout/index.js
>        currentScreen = <TimeSheets />;
Timesheet is written together. So the route should be named /timesheets

2022-11-01 15:24 UTC, ignacioaristo requested changes
Change all the components to arrow function.

2022-11-01 17:43 UTC, matescarabino commented on src/Components/TimeSheets/Form/index.js
> +        console.error(error);
Done

2022-11-01 17:44 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +    saveList([...timeSheet.filter((timeSheet) => timeSheet._id !== id)]);
Done

2022-11-01 17:45 UTC, matescarabino commented on src/Components/Layout/index.js
>        currentScreen = <TimeSheets />;
It was like that on the base file but it makes sense. Done

2022-11-01 17:47 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +      console.error(error);
Done

2022-11-01 17:50 UTC, matescarabino commented on src/Components/TimeSheets/index.js
>  function TimeSheets() {
Done

2022-11-01 17:54 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +  const [timeSheet, saveList] = useState([]);
Done

2022-11-02 00:51 UTC, ignacioaristo requested changes
The name of the folder must be with cameCasel convention.

2022-11-02 00:51 UTC, ignacioaristo commented on src/Components/TimeSheets/Form/Form Title/index.js
> +function FormText(props) {
Is this component necessary? I think we just could put the title in the index.js of the form.

2022-11-02 12:23 UTC, ignacioaristo approved these changes

2022-11-02 13:36 UTC, renzopimentel approved these changes
Seems to be everything ok, approved 👌🏻

2022-11-02 13:48 UTC, MaxiG-dev approved these changes
Everything looks great!

2022-11-02 13:50 UTC, merged

2022-11-04 19:03 UTC, julianpiaggio reviewed
🕵️‍♂️ **QA FEEDBACK**

**TIME SHEETS**

First of all, we wanted to tell you that we consider that your pr complies
the requirements to be approved, and that you can merge to the master branch 👍

Now, if we consider leaving you some comments:

* in the create action, the description field allows only spaces, only numbers, and only characters.
 What we consider necessary would be to be able to add a validation that yes or yes contains letters and that
these may be accompanied by other characters.

* in the date field it allows to put numbers very far from the current one (eg: 01/01/0001). The advisable
it would be to put a minimum value so that it can be considered correct.

in the hours field, you can put 0 as a value, being inconsistent with the functionality of the field,
since it describes exactly how many hours are worked. It is recommended to put greater than 0

Below we leave details in images and a link that accesses a video to be able to reproduce and be more clear about the aforementioned details:

![error timesheets](https://user-images.githubusercontent.com/84697592/200054591-1f7275c3-5edf-49a9-9716-918a53dea9dd.png)

https://imgur.com/a/FBrzpAs