BaSP-TG-62: Shared table component
BaSP-a2022/ayom-a-trackgenix-app pull request #11
Opened 2022-11-08 05:11 UTC by Ansitox

2022-11-08 12:43 UTC, nicolasblasco requested changes

2022-11-08 12:43 UTC, nicolasblasco commented on src/Components/Shared/Table/Table.js
> +const Table = (props) => {
It would be better if we destructure the props, like this {data, header,...}

2022-11-08 12:43 UTC, nicolasblasco commented on src/Components/Shared/Table/Table.js
> +      />
We shouldn't have the modal component inside the table component

2022-11-08 12:43 UTC, nicolasblasco commented on src/Components/Shared/Table/Table.js
> +  };
All of this logic should go outside of the table component

2022-11-08 19:13 UTC, Ansitox commented on src/Components/Shared/Table/Table.js
> +const Table = (props) => {
Done.

2022-11-08 19:13 UTC, Ansitox commented on src/Components/Shared/Table/Table.js
> +      />
Done.

2022-11-08 19:13 UTC, Ansitox commented on src/Components/Shared/Table/Table.js
> +  };
Done.

2022-11-08 19:47 UTC, matescarabino requested changes
Only that typo, everything else works fine

2022-11-08 19:47 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +    if (timeSheet.task == null && timeSheet.employee == null && timeSheet.projet == null) {
"project" has a typo (projet), that's why is was not showing right on the table
```suggestion
    if (timeSheet.task == null && timeSheet.employee == null && timeSheet.project== null) {
```

2022-11-08 19:47 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task == null && timeSheet.employee == null && timeSheet.projet !== null) {
Same as before

2022-11-08 19:47 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task == null && timeSheet.employee !== null && timeSheet.projet == null) {
Same as before

2022-11-08 19:47 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task !== null && timeSheet.employee == null && timeSheet.projet == null) {
Same as before

2022-11-08 19:47 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task == null && timeSheet.employee !== null && timeSheet.projet !== null) {
Same as before

2022-11-08 19:47 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task !== null && timeSheet.employee == null && timeSheet.projet !== null) {
Same as before

2022-11-08 19:47 UTC, matescarabino commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task !== null && timeSheet.employee !== null && timeSheet.projet == null) {
Same as before

2022-11-08 20:03 UTC, Ansitox commented on src/Components/TimeSheets/index.js
> +    if (timeSheet.task == null && timeSheet.employee == null && timeSheet.projet == null) {
fixed

2022-11-08 20:04 UTC, Ansitox commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task == null && timeSheet.employee == null && timeSheet.projet !== null) {
fixed

2022-11-08 20:04 UTC, Ansitox commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task !== null && timeSheet.employee == null && timeSheet.projet == null) {
fixed

2022-11-08 20:04 UTC, Ansitox commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task !== null && timeSheet.employee == null && timeSheet.projet !== null) {
fixed

2022-11-08 20:04 UTC, Ansitox commented on src/Components/TimeSheets/index.js
> +    } else if (timeSheet.task !== null && timeSheet.employee !== null && timeSheet.projet == null) {
fixed

2022-11-08 20:06 UTC, matescarabino approved these changes

2022-11-08 23:51 UTC, ignacioaristo requested changes

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/Admins/index.js
> +  // eslint-disable-next-line no-unused-vars
You leave this in every entity, is on purpose for something? Because you are not using this variable, in case those useStates are unnecessary delete all.

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/Admins/index.js
> +      let response = await fetch(`${process.env.REACT_APP_API_URL}/admin`);
change to const

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/Admins/index.js
> +  // eslint-disable-next-line no-unused-vars
Same here, maybe you are waiting for the modal component? Let me know

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/TimeSheets/index.js
> +      let response = await fetch(`${process.env.REACT_APP_API_URL}/timesheets/`);
change to const

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/TimeSheets/index.js
> +        task: `${timeSheet.project['description']}`,
this brings the project description instead of the task. 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/72083744/200699962-1e65849a-68db-4ae6-a707-9f99e267bdbd.png">

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/Employees/index.js
> +      let response = await fetch(`${process.env.REACT_APP_API_URL}/employees/`);
change to const

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/Projects/index.js
> +      let response = await fetch(`${process.env.REACT_APP_API_URL}/projects`);
change to const

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/Shared/Table/Table.module.css
> +table {
careful, element tags could bring problems with module.css. Use classes instead.

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/SuperAdmins/index.js
>        let response = await fetch(`${process.env.REACT_APP_API_URL}/superAdmin/`);
change to const

2022-11-08 23:51 UTC, ignacioaristo commented on src/Components/Tasks/index.js
> +      let response = await fetch(`${process.env.REACT_APP_API_URL}/tasks`);
change to const

2022-11-09 01:10 UTC, Ansitox commented on src/Components/Admins/index.js
> +  // eslint-disable-next-line no-unused-vars
Exactly, I leave those there to be used with the modals. should I delete them anyways?

2022-11-09 19:47 UTC, Ansitox commented on src/Components/TimeSheets/index.js
> +        task: `${timeSheet.project['description']}`,
Fixed

2022-11-09 23:36 UTC, MaxiG-dev approved these changes
Everything looks great!

2022-11-10 17:10 UTC, nicolasblasco approved these changes

2022-11-10 17:35 UTC, ignacioaristo approved these changes

2022-11-10 21:06 UTC, NicoSan02 approved these changes

2022-11-10 21:07 UTC, merged