BaSP-TG-61: Shared button component
BaSP-a2022/ayom-a-trackgenix-app pull request #12
Opened 2022-11-08 18:34 UTC by melissabonillasellanes

- Create a shared button component with two variants: primary and secondary
- Refactor in all the components where buttons are being used with the new props structure

2022-11-08 18:51 UTC, matescarabino approved these changes
Everything looks fine

2022-11-08 19:22 UTC, Ansitox approved these changes

2022-11-08 23:38 UTC, nicolasblasco requested changes

2022-11-08 23:38 UTC, nicolasblasco commented on src/Components/Shared/Button/index.js
> +    <button type={type ? type : 'button'} className={`${styles[variant]}`} onClick={onClick}>
We should add disabled as a prop

2022-11-08 23:38 UTC, nicolasblasco commented on package.json
> +    "react-router-dom": "^5.3.4",
We should watch out if we change the version of react router dom

2022-11-08 23:38 UTC, nicolasblasco commented on src/Components/Shared/Button/button.module.css
> +.confirm {
Maybe we could rename this class to primary

2022-11-08 23:38 UTC, nicolasblasco commented on src/Components/Shared/Button/button.module.css
> +.cancel {
Maybe we could rename this class to secondary

2022-11-09 00:19 UTC, nicolasblasco approved these changes

2022-11-09 03:59 UTC, julianpiaggio requested changes
🕵️‍♂️ QA FEEDBACK


First of all, we wanted to tell you that in order to approve this pr, some modifications need to be applied
that affect the functionality of the application. ⏰

This is:

* in the action of editing the superadmin, when wanting to confirm the update, it throws a banner without info and does not even return to the home screen. if we immediately press the confirm button again, it throws a banner with the legend "TypeError: Failed to fetch"

Then I leave you a link with a video of the error:
https://imgur.com/a/OEM4DU9


* in the creation of an employee when pressing the confirm button, it does not return to the initial page but stays on the same create screen

Then I leave you a link with a video of the error:
https://imgur.com/a/DZlAUtL

* in the update of employees when confirming the modification of an employee does not return to the initial page, but stays on the same screen.

Then I leave you a link with a video of the error:
https://imgur.com/a/AFjvgR1

2022-11-09 17:09 UTC, julianpiaggio approved these changes

2022-11-09 19:01 UTC, merged