BaSP-TG-64: Shared confirmation modal component
BaSP-a2022/ayom-a-trackgenix-app pull request #14
Opened 2022-11-09 02:39 UTC by MaxiG-dev

-Create modal component
-Implement modal in all entities

2022-11-10 01:19 UTC, ignacioaristo requested changes

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Shared/Modal/Modal.confirm.js
> +  return show ? (
use `&&` operator

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Shared/Modal/modal.module.css
> +  background-color: white;
use HEX convention.

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Shared/Modal/modal.module.css
> +  color: white;
use HEX convention

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Shared/Modal/modal.module.css
> +  color: black;
use HEX convention

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Employees/Form/index.js
> +import ModalMessage from '../../Shared/Modal/Modal.message';
Is this component created?

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Employees/Form/index.js
> +    id ? editEmployee() : createEmployee();
use && operator

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Employees/Form/index.js
> +      {modalConfirm ? (
use `$$` operator

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Employees/List/List.js
> +                      modalTitle={'Delete employee'}
Move the text in a outside variable

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Employees/List/List.js
> +                      modalContent={`Are you sure you want to delete employee whit ID ${employee.name}`}
Same here

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Projects/Form/index.js
> +  const modalFunction = async () => {
rename the function for something more specific

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Projects/Form/index.js
> +      {modalConfirm ? (
use `$$` operator

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Projects/ListItems/index.js
>  import './listItem.module.css';
is this right?

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Projects/ListItems/index.js
> +        modalTitle={'Delete task'}
Move this text in a outside variable

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Projects/ListItems/index.js
> +        modalContent={`Are you sure you want to delete task ${listItem.description} whit ID ${listItem._id}`}
Same here

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Shared/Modal/modal.module.css
> +  background-color: white;
change to HEX convention

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Shared/Modal/modal.module.css
> +  background-color: red;
change to HEX convention

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Shared/Modal/modal.module.css
> +  color: white;
change to HEX convention

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Shared/Modal/modal.module.css
> +  color: black;
change to HEX convention

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/SuperAdmins/Form/Form.js
> +        modalTitle={'Update admin'}
Move the text in a outside variable

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/SuperAdmins/Form/Form.js
> +        modalContent={`Are you sure you want to Update admin whit ID ${id}`}
Move the text in a outside variable

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/SuperAdmins/List/ListItem/ListItem.js
> +        modalTitle={'Delete super admin'}
Move the text in a outside variable

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/SuperAdmins/List/ListItem/ListItem.js
> +        modalContent={`Are you sure you want to delete Super Admin whit ID ${listItem._id}`}
Move the text in a outside variable

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Tasks/TaskList/ListItem.js
> +        modalTitle={'Delete task'}
Move the text in a outside variable

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Tasks/TaskList/ListItem.js
> +        modalContent={`Are you sure you want to delete task ${taskList.description} whit ID ${taskList._id}`}
Move the text in an outside variable

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/Admins/Form/index.js
>    const onSubmit = async (e) => {
async is necessary here? You are not using await.

2022-11-10 01:19 UTC, ignacioaristo commented on src/Components/SuperAdmins/Form/Form.js
>    const onSubmit = async (e) => {
is async necessary?

2022-11-10 23:16 UTC, MaxiG-dev commented on src/Components/Admins/Form/index.js
> +import ModalConfirm from '../../Shared/Modal/Modal.confirm';
Done!

2022-11-10 23:25 UTC, MaxiG-dev commented on src/Components/Admins/Form/index.js
>    const id = params.Id ? params.Id : '';
Done!

2022-11-11 05:20 UTC, MaxiG-dev commented on src/Components/Shared/Modal/Modal.confirm.js
> +  return show ? (
Done!

2022-11-11 05:21 UTC, MaxiG-dev commented on src/Components/Shared/Modal/modal.module.css
> +  background-color: white;
Done!

2022-11-11 05:22 UTC, MaxiG-dev commented on src/Components/Shared/Modal/modal.module.css
> +  color: black;
Done!

2022-11-11 05:22 UTC, MaxiG-dev commented on src/Components/Employees/Form/index.js
> +import ModalMessage from '../../Shared/Modal/Modal.message';
Done!

2022-11-11 05:24 UTC, MaxiG-dev commented on src/Components/Employees/Form/index.js
> +    id ? editEmployee() : createEmployee();
In this case if an id exists I want to execute edit Employee in case it doesn't exist I want to execute create Employee

2022-11-11 05:24 UTC, MaxiG-dev commented on src/Components/Employees/Form/index.js
> +      {modalConfirm ? (
Done!

2022-11-11 05:24 UTC, MaxiG-dev commented on src/Components/Employees/List/List.js
> +                      modalTitle={'Delete employee'}
Done!

2022-11-11 05:24 UTC, MaxiG-dev commented on src/Components/Projects/Form/index.js
> +  const modalFunction = async () => {
Done!

2022-11-11 05:25 UTC, MaxiG-dev commented on src/Components/Projects/Form/index.js
> +      {modalConfirm ? (
Done!

2022-11-11 05:25 UTC, MaxiG-dev commented on src/Components/Projects/ListItems/index.js
>  import './listItem.module.css';
This file was deleted

2022-11-11 05:25 UTC, MaxiG-dev commented on src/Components/Projects/ListItems/index.js
> +        modalTitle={'Delete task'}
Done!

2022-11-11 05:26 UTC, MaxiG-dev commented on src/Components/Projects/ListItems/index.js
> +        modalTitle={'Delete task'}
This file was deleted

2022-11-11 05:26 UTC, MaxiG-dev commented on src/Components/Projects/ListItems/index.js
> +        modalContent={`Are you sure you want to delete task ${listItem.description} whit ID ${listItem._id}`}
This file was deleted

2022-11-11 05:26 UTC, MaxiG-dev commented on src/Components/Shared/Modal/modal.module.css
> +  background-color: white;
Done!

2022-11-11 05:26 UTC, MaxiG-dev commented on src/Components/Shared/Modal/modal.module.css
> +  color: white;
Done!

2022-11-11 05:26 UTC, MaxiG-dev commented on src/Components/Shared/Modal/modal.module.css
> +  color: black;
Done!

2022-11-11 05:26 UTC, MaxiG-dev commented on src/Components/Shared/Modal/modal.module.css
> +  background-color: red;
Done!

2022-11-11 05:27 UTC, MaxiG-dev commented on src/Components/SuperAdmins/Form/Form.js
> +        modalTitle={'Update admin'}
Done!

2022-11-11 05:27 UTC, MaxiG-dev commented on src/Components/SuperAdmins/List/ListItem/ListItem.js
> +        modalTitle={'Delete super admin'}
This file was deleted

2022-11-11 05:27 UTC, MaxiG-dev commented on src/Components/SuperAdmins/Form/Form.js
> +        modalContent={`Are you sure you want to Update admin whit ID ${id}`}
Done!

2022-11-11 05:27 UTC, MaxiG-dev commented on src/Components/SuperAdmins/List/ListItem/ListItem.js
> +        modalContent={`Are you sure you want to delete Super Admin whit ID ${listItem._id}`}
This file was deleted

2022-11-11 05:27 UTC, MaxiG-dev commented on src/Components/Tasks/TaskList/ListItem.js
> +        modalTitle={'Delete task'}
This file was deleted

2022-11-11 05:27 UTC, MaxiG-dev commented on src/Components/Tasks/TaskList/ListItem.js
> +        modalContent={`Are you sure you want to delete task ${taskList.description} whit ID ${taskList._id}`}
This file was deleted

2022-11-11 05:29 UTC, MaxiG-dev commented on src/Components/Admins/Form/index.js
>    const onSubmit = async (e) => {
Done!

2022-11-11 05:30 UTC, MaxiG-dev commented on src/Components/SuperAdmins/Form/Form.js
>    const onSubmit = async (e) => {
Done!

2022-11-11 15:44 UTC, CristianBucci commented on src/Components/Shared/Modal/Modal.js
> +
Split each modal into a separate component!

2022-11-11 15:45 UTC, CristianBucci commented on src/Components/Shared/Modal/Modal.js
Split each modal into a separate component!

2022-11-11 15:48 UTC, CristianBucci commented on src/Components/Shared/Modal/Modal.js
> +
Move the delete function out of the component, put it in a "Utils" folder for example.

2022-11-11 18:40 UTC, CristianBucci commented on src/Components/Shared/Modal/Modal.js
Done!

2022-11-11 18:40 UTC, CristianBucci commented on src/Components/Shared/Modal/Modal.js
> +
Done!

2022-11-11 18:44 UTC, CristianBucci approved these changes

2022-11-11 19:06 UTC, nicolasblasco approved these changes

2022-11-11 20:20 UTC, julianpiaggio requested changes
🕵️‍♂️ QA FEEDBACK

First of all, we wanted to tell you that we consider that your pr complies
the requirements to be approved, and that it can be merged into the master branch 👍

Now, if we consider leaving you some comments:

*  when I go to create an employee, I get a banner with the message "Could not GET employee! Cannot read properties of undefined (reading 'name')". This access should not be impeded, since when entering the loading form it would be necessary to be able to load the data without any problem.

2022-11-11 20:33 UTC, julianpiaggio approved these changes

2022-11-11 20:33 UTC, merged