BaSP-TG-63: Shared modal component
BaSP-a2022/ayom-a-trackgenix-app pull request #15
Opened 2022-11-09 02:45 UTC by MaxiG-dev

-Create modal messages component

2022-11-09 23:54 UTC, CristianBucci commented on src/Components/Shared/Modal/modal.module.css
> +}
Please set the properties order like this:
- Position 
- Display.
- Flexbox (flex-direction, align-self, etc).
- Box-model: width, height, margin, padding, top, left, etc.
- Background y border.
- Text (font-size, text-shadow, etc).
- Other rules

2022-11-09 23:57 UTC, nicolasblasco requested changes

2022-11-09 23:57 UTC, nicolasblasco commented on src/Components/Shared/Modal/Modal.message.js
> +    ''
We should return null instead of an empty string

2022-11-10 00:35 UTC, ignacioaristo approved these changes

2022-11-10 00:35 UTC, ignacioaristo commented on src/Components/Shared/Modal/Modal.message.js
> +    ''
If we only want to show it when show is equal to true we could use the `&&` operator.
Like this:
`return show && (......)
`
With that, we avoid use the ternary in the wrong way.

2022-11-10 00:37 UTC, MaxiG-dev commented on src/Components/Shared/Modal/modal.module.css
> +}
Done!

2022-11-10 01:06 UTC, nicolasblasco requested changes

2022-11-10 01:06 UTC, nicolasblasco commented on src/Components/Shared/Modal/Modal.message.js
> +export default ModalMessage;
We should rename the component to Modal.js

2022-11-10 01:10 UTC, CristianBucci approved these changes

2022-11-10 01:44 UTC, MaxiG-dev commented on src/Components/Shared/Modal/Modal.message.js
> +export default ModalMessage;
Done!

2022-11-10 01:44 UTC, MaxiG-dev commented on src/Components/Shared/Modal/Modal.message.js
> +    ''
Done!

2022-11-10 02:16 UTC, nicolasblasco approved these changes

2022-11-10 02:16 UTC, merged