TG-43: super admin entity
BaSP-a2022/ayom-a-trackgenix-app pull request #2
Opened 2022-10-31 20:38 UTC by Ansitox

2022-11-01 01:49 UTC, matescarabino commented on src/Components/SuperAdmins/Form/Form.js
> +      if (response.status === 200) {
wouldn't it be 201?

2022-11-01 01:51 UTC, matescarabino commented
It looks fine to me

2022-11-01 12:41 UTC, matescarabino commented on src/Components/SuperAdmins/Form/Form.js
> +      console.log(response);
Remove before merge

2022-11-01 12:43 UTC, matescarabino commented on src/Components/SuperAdmins/index.js
> +      console.log(error);
```suggestion
      console.error(error);
```

2022-11-01 14:48 UTC, Ansitox commented on src/Components/SuperAdmins/Form/Form.js
> +      console.log(response);
Done.

2022-11-01 15:46 UTC, ignacioaristo requested changes
Change all the components to arrow functions

2022-11-01 15:46 UTC, ignacioaristo commented on src/Components/SuperAdmins/Form/Form.js
> +  const handler = () => {
we need be more specific for this function's name

2022-11-01 15:46 UTC, ignacioaristo commented on src/Components/SuperAdmins/List/List.module.css
> +.table {
move all the tag selector above. Then the classes.

2022-11-01 15:46 UTC, ignacioaristo commented on src/Components/SuperAdmins/index.js
> +  const [err, setError] = useState('');
In order to follow good practices, name the setState function `setErr`

2022-11-01 15:46 UTC, ignacioaristo commented on src/Components/SuperAdmins/index.js
> +  useEffect(async () => {
You are handle the catch here, but you are handling the error when you created, so, in this useEffect you only have to invoke the function.

2022-11-01 16:48 UTC, Ansitox commented on src/Components/SuperAdmins/index.js
> +  useEffect(async () => {
Done.

2022-11-01 16:48 UTC, Ansitox commented on src/Components/SuperAdmins/index.js
> +  const [err, setError] = useState('');
Done.

2022-11-01 16:48 UTC, Ansitox commented on src/Components/SuperAdmins/List/List.module.css
> +.table {
Done.

2022-11-01 16:48 UTC, Ansitox commented on src/Components/SuperAdmins/Form/Form.js
> +  const handler = () => {
Done.

2022-11-02 14:43 UTC, matescarabino approved these changes

2022-11-02 23:59 UTC, MaxiG-dev approved these changes
Everything looks great!

2022-11-03 13:52 UTC, ignacioaristo approved these changes

2022-11-04 18:37 UTC, NicoSan02 approved these changes
🕵️‍♂️ **QA FEEDBACK**

**SUPER ADMIN**

First of all, we wanted to let you know that we consider that **your PR complies
the requirements to be approved**, and that you can merge to the master branch 👍

however we consider leaving you some comments:

*when creating or editting, Name, Last Name or Password are invalid, the modal displayed contains a confusing message.

![modal error](https://user-images.githubusercontent.com/107139347/200041597-c24675ed-ebfa-4810-bfa9-1df56367c390.png)

2022-11-04 18:38 UTC, merged