BaSP-TG-79: Projects redux get
BaSP-a2022/ayom-a-trackgenix-app pull request #21
Opened 2022-11-13 13:21 UTC by Ansitox

-Create constants to get projects
-Create actions to get projects
-Create thunk to get projects
-Create projects reducer
-Connect list component with store to get projects

For QAs:
You should see the table and, for an instant, a loading spinner when the list is fetching. If an error occurs doing the fetch a message will display on a modal.

2022-11-13 14:49 UTC, CristianBucci commented on src/Components/Projects/projects.module.css
> +  height: 3em;
Use px instead of em!

2022-11-13 15:20 UTC, CristianBucci approved these changes

2022-11-13 17:57 UTC, nicolasblasco requested changes

2022-11-13 17:57 UTC, nicolasblasco commented on src/redux/projects/thunks.js
> +      return data.data;
We don't need to return because we already have an action that saves the data

2022-11-13 17:57 UTC, nicolasblasco commented on src/redux/projects/reducer.js
> +  isPending: false,
I think "isLoading" is a better description of this variable

2022-11-13 17:57 UTC, nicolasblasco commented on src/redux/projects/actions.js
> +const getProjectsPending = () => {
We could directly export the action

2022-11-13 17:57 UTC, nicolasblasco commented on src/redux/projects/actions.js
> +const getProjectsSuccess = (data) => {
We could directly export the action

2022-11-13 17:57 UTC, nicolasblasco commented on src/redux/projects/actions.js
> +const getProjectsError = (error) => {
We could directly export the action

2022-11-13 17:57 UTC, nicolasblasco commented on src/redux/projects/actions.js
> +const messageModalClose = () => {
We could directly export the action

2022-11-13 17:57 UTC, nicolasblasco commented on src/redux/projects/actions.js
> +export default messageModalClose;
If we directly export each action independently we could remove these lines

2022-11-13 20:20 UTC, nicolasblasco commented on src/Components/Projects/index.js
> +  }
I think we could put the spinner where the table is so that when is loading is true the app renders the spinner and when it is false it renders the table. We can check this PR https://github.com/BaSP-a2022/ayom-a-trackgenix-app/pull/20

2022-11-13 22:51 UTC, ignacioaristo requested changes

2022-11-13 22:51 UTC, ignacioaristo commented on src/Components/Projects/index.js
> +  //const [showModalMessage, setShowModalMessage] = useState(false);
Remove these commets

2022-11-13 22:51 UTC, ignacioaristo commented on src/Components/Projects/index.js
> +    // setModalContent({
If this is not necessary, remove this comments

2022-11-13 22:51 UTC, ignacioaristo commented on src/Components/Projects/index.js
> +    //setList: setProjects
These too.

2022-11-14 12:56 UTC, ignacioaristo approved these changes

2022-11-14 16:04 UTC, nicolasblasco approved these changes

2022-11-14 16:05 UTC, merged