TG: 50 - Readme
BaSP-a2022/ayom-a-trackgenix-app pull request #3
Opened 2022-11-01 20:01 UTC by melissabonillasellanes

Update Readme (APP)

2022-11-02 12:28 UTC, ignacioaristo requested changes
We could add info about what Trackgenix does, witch technologies we are using for develop de app, etc.

2022-11-03 00:03 UTC, MaxiG-dev requested changes

2022-11-03 00:03 UTC, MaxiG-dev commented on README.md
> +
You can change my email "maximilianogonzalezit@gmail.com" to "maxig.dev@gmail.com", this is my email for github.
Sorry for the confusion, my bad :S

2022-11-04 04:39 UTC, MaxiG-dev approved these changes
Everything looks great!

2022-11-04 15:57 UTC, ignacioaristo approved these changes

2022-11-04 16:03 UTC, merged