BaSP-TG-100: Form - Employee
BaSP-a2022/ayom-a-trackgenix-app pull request #35
Opened 2022-11-19 15:21 UTC by matescarabino

- Add a redux thunk to GET the entity by its ID
- Change some logic to make form work with new getByIdEmployee() thunk
- Implement react-hook-form
- Implement Joi validations and resolver

**How to test QA**:
1- Navigate to employee entity in the navbar

2- Test **create** employee work as intended
    2.1- Test new "reset" button, it should reset every field to blank
    2.2- Test error messages (check ticket TG-100 Joi validations)

3- Test **update** employee work as intended
    3.1- Test new "reset" button, it should reset every field to the original value
    3.2- Test error messages (check ticket TG-100 Joi validations)

2022-11-19 16:06 UTC, CristianBucci approved these changes
Everything looks right to me!

2022-11-19 18:27 UTC, Ansitox approved these changes
Looks good to me

2022-11-19 23:36 UTC, ignacioaristo requested changes

2022-11-19 23:36 UTC, ignacioaristo commented on src/Components/Employees/Form/validations.js
> +      'string.pattern.base': 'All characters must be letters.'
Custom all the messages (min and requierd too)

2022-11-19 23:36 UTC, ignacioaristo commented on src/Components/Employees/Form/validations.js
> +      'string.pattern.base': 'All characters must be letters.'
same in all the validations

2022-11-20 00:14 UTC, matescarabino commented on src/Components/Employees/Form/validations.js
> +      'string.pattern.base': 'All characters must be letters.'
done

2022-11-20 00:14 UTC, matescarabino commented on src/Components/Employees/Form/validations.js
> +      'string.pattern.base': 'All characters must be letters.'
done

2022-11-20 16:40 UTC, ignacioaristo approved these changes

2022-11-20 22:05 UTC, julianpiaggio reviewed
🕵️‍♂️ QA FEEDBACK

We wanted to tell you that we consider that your pr complies
the requirements to be approved, and that it can be merged into the master branch 👍

2022-11-20 22:05 UTC, merged