BaSP-TG-99: Form - Super admin
BaSP-a2022/ayom-a-trackgenix-app pull request #36
Opened 2022-11-19 18:08 UTC by Ansitox

- Add a redux thunk to GET the entity by its ID
- Change some logic to make form work with new getByIdEmployee() thunk
- Implement react-hook-form
- Implement Joi validations and resolver

How to test QA:
1- Navigate to super admins entity in the navbar

2- Test create employee work as intended
2.1- Test new "reset" button, it should reset every field to blank
2.2- Test error messages (check ticket TG-99 Joi validations)

3- Test update employee work as intended
3.1- Test new "reset" button, it should reset every field to the original value
3.2- Test error messages (check ticket TG-99 Joi validations)

2022-11-19 18:37 UTC, matescarabino approved these changes
Looks fine

2022-11-19 23:39 UTC, ignacioaristo requested changes

2022-11-19 23:39 UTC, ignacioaristo commented on src/Components/SuperAdmins/Form/validations.js
> +    .messages({
custom all the messages ( min, required)

2022-11-19 23:39 UTC, ignacioaristo commented on src/Components/SuperAdmins/Form/validations.js
> +  lastName: Joi.string()
same in all the messages

2022-11-20 05:02 UTC, Ansitox commented on src/Components/SuperAdmins/Form/validations.js
> +  lastName: Joi.string()
done

2022-11-20 05:02 UTC, Ansitox commented on src/Components/SuperAdmins/Form/validations.js
> +    .messages({
done

2022-11-20 14:16 UTC, CristianBucci approved these changes
Everything looks good to me!

2022-11-20 16:31 UTC, CristianBucci approved these changes
Everything looks right!

2022-11-20 17:19 UTC, NicoSan02 approved these changes

2022-11-20 17:41 UTC, merged