BaSP-TG-101: Form - projects
BaSP-a2022/ayom-a-trackgenix-app pull request #38
Opened 2022-11-19 21:27 UTC by MaxiG-dev

- Add a redux thunk to GET the entity by its ID
- Implement react-hook-form
- Implement resolver
- Implement Joi validations (see description)
- Implement error messages for validations

2022-11-19 21:38 UTC, Ansitox requested changes
Remember to add a reset button in the form to clean the inputs

2022-11-19 21:39 UTC, Ansitox requested changes
The rate inputs are not being validated

2022-11-19 23:28 UTC, matescarabino requested changes
The reset button should leave the input Values as they came to the form. If it came through the create it will be blank and if it came through the edit it will be the same data

2022-11-19 23:41 UTC, ignacioaristo submitted a review, later dismissed

2022-11-19 23:41 UTC, ignacioaristo commented on src/Components/Projects/Form/validations.js
> +export const projectsSchema = Joi.object({
custom all the messages of the validations.

2022-11-20 13:45 UTC, matescarabino requested changes
The reset button when editing doesn't bring back the previously deleted employees.

2022-11-20 17:13 UTC, Ansitox approved these changes

2022-11-20 18:51 UTC, matescarabino approved these changes
Approved this week's work. I leave in slack a little thing that would have to fix for the final delivery.

2022-11-20 21:17 UTC, julianpiaggio approved these changes
🕵️‍♂️ QA FEEDBACK


First of all, we wanted to tell you that we consider that your pr complies
the requirements to be approved, and that it can be merged into the master branch 👍

Now, if we consider leaving you some comments:

* When entering when creating and wanting to confirm with the empty fields, all the errors do not jump, but each required individually. Only when entering and putting data in the fields do the validations jump with their corresponding messages. What is expected is that when doing this test and wanting to confirm, all the fields will mark their respective errors at the same time, as in the rest of the dependencies.

![projects-week-14](https://user-images.githubusercontent.com/84697592/202926373-046f2727-d22b-4ed7-a50a-dbecf90375b3.png)


* Having at least two employees in the project and wanting to delete one, always delete the last one. The expected thing would be to delete the option chosen by oneself.

Here we leave you a detailed link with a video that describes what we tell you:
https://imgur.com/a/ueiI5ej

2022-11-20 21:38 UTC, MaxiG-dev commented on src/Components/Projects/Form/validations.js
> +export const projectsSchema = Joi.object({
Done!

2022-11-20 21:43 UTC, merged