BaSP-TG-47: Employees entity
BaSP-a2022/ayom-a-trackgenix-app pull request #4
Opened 2022-11-02 00:39 UTC by renzopimentel

2022-11-02 01:52 UTC, matescarabino requested changes

2022-11-02 01:52 UTC, matescarabino commented on src/Components/Employees/Form/index.js
> +        console.error(error);
Remove console.errors and console.logs before merge

2022-11-02 01:52 UTC, matescarabino commented on src/Components/Employees/Modal/index.js
> +console.log(styles);
Remove

2022-11-02 01:52 UTC, matescarabino commented on src/Components/Employees/index.js
> +      console.error(error);
```suggestion
      alert('Error example...', error);
```

2022-11-02 13:15 UTC, matescarabino requested changes

2022-11-02 13:15 UTC, matescarabino commented on src/Components/Employees/index.js
> +      console.log('data', json.data);
Remove console.logs and console.errors before merge

2022-11-02 14:08 UTC, MaxiG-dev commented on src/Components/Employees/Form/index.js
> +  var product = urlParams.get('id');
maybe you can change var to let or const

2022-11-02 14:30 UTC, renzopimentel commented on src/Components/Employees/Form/index.js
> +  var product = urlParams.get('id');
Thanks! I forgot to change it

2022-11-02 14:31 UTC, matescarabino approved these changes

2022-11-02 16:32 UTC, CristianBucci commented on src/Components/Employees/List/list.module.css
> +}
`text-align: center; ` this should be in position;

2022-11-02 16:32 UTC, nicolasblasco requested changes

2022-11-02 16:32 UTC, nicolasblasco commented on src/Components/Employees/Form/index.js
> +  let product = urlParams.get('id');
We could rename this variable to be more specific, like employeeId

2022-11-02 16:32 UTC, nicolasblasco commented on src/Components/Employees/Form/index.js
> +  if (idRegEx.test(product)) {
There is no need to test the id format

2022-11-02 16:32 UTC, nicolasblasco commented on src/Components/Employees/Form/index.js
> +        alert(error);
We could use the setContentMessage instead of an alert

2022-11-02 16:34 UTC, CristianBucci commented on src/Components/Employees/Modal/modal.module.css
> +  }
the correct order should be:
  .screen {
    display: flex;
    position: absolute;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    **width: 100vw;
    height: 100vh**;
    background-color: #00000074;
  }

2022-11-02 16:36 UTC, CristianBucci commented on src/Components/Employees/Modal/modal.module.css
> +  }
This should be:

` .modal {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 25%;
    min-height: 10em;
    background-color: white;
    border-radius: 10px;    
    box-shadow: 0 0 2px rgba(0, 0, 0, 0.432);
  }`

2022-11-02 16:38 UTC, CristianBucci commented on src/Components/Employees/Modal/modal.module.css
> +    padding-bottom: 10px;
This shloud be:

    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    width: 90%;
    margin-top: 10px;    
    padding-bottom: 10px;
    border-bottom: 1px solid rgba(0, 0, 0, 0.132);

2022-11-02 17:39 UTC, renzopimentel commented on src/Components/Employees/index.js
> +    setEmployees([...employees.filter((employee) => employee._id !== id)]);
Done

2022-11-02 17:39 UTC, renzopimentel commented on src/Components/Employees/Modal/modal.module.css
> +  }
Done

2022-11-02 17:39 UTC, renzopimentel commented on src/Components/Employees/Modal/modal.module.css
> +  }
Done

2022-11-02 17:40 UTC, renzopimentel commented on src/Components/Employees/Form/index.js
> +        alert(error);
Done

2022-11-02 17:40 UTC, renzopimentel commented on src/Components/Employees/Form/index.js
> +  if (idRegEx.test(product)) {
Done

2022-11-02 17:48 UTC, renzopimentel commented on src/Components/Employees/index.js
> +      alert(error);
Done

2022-11-02 23:45 UTC, MaxiG-dev requested changes
I found a detail about the consistency of the code, I did not find any more errors.

2022-11-02 23:45 UTC, MaxiG-dev commented on src/Components/Employees/index.js
>        setEmployees(json.data);
In the file .../Employees/Form/index.js you use `const data = await response.json();` instead of  `const data = await response.json();`

Maybe you can use the same in both cases so that the code is to be consistent.

2022-11-02 23:45 UTC, MaxiG-dev commented on src/Components/Employees/Form/index.js
> +      setNameValue(data.data.name);
In the file .../Employees/index.js you use `const data = await response.json();` instead of `const data = await response.json();`

Maybe you can use the same in both cases so that the code is to be consistent.

2022-11-03 12:24 UTC, renzopimentel commented on src/Components/Employees/Form/index.js
> +      setNameValue(data.data.name);
Done! All the consts are named data now

2022-11-03 13:20 UTC, MaxiG-dev approved these changes
Everything looks great!

2022-11-03 13:56 UTC, nicolasblasco approved these changes

2022-11-03 14:46 UTC, CristianBucci approved these changes

2022-11-04 20:35 UTC, julianpiaggio requested changes
🕵️‍♂️ **QA FEEDBACK**

**EMPLOYEE**

First of all, we wanted to tell you that in order to approve this pr, some modifications need to be applied
that affect the functionality of the application. ⏰

This is:

* in the create action, both to leave the fields empty and to enter invalid data, the save button
redirects to a wrong page. This directly affects the operation of the app and the solution
is that this button throws the required answers in front of each scenario as eg (if the fields are empty,
When pressing this button a sign should appear saying "the fields cannot be left empty")

Here we leave you a detailed link with a video that describes what we tell you:
https://imgur.com/a/Z3o5cya


Here are some other possible improvements:

* when the creation of the employee is successful, it throws a poster that, although it confirms it, remains in
 the same page. This could be improved, if when confirming said action, it would return to the initial screen
of employee with the new data already loaded.

![error employee](https://user-images.githubusercontent.com/84697592/200069311-419b714f-644e-40c3-87e6-2e5c5196f223.png)


* the delete action does not provide a confirmation message to complete it. This confirmation is recommended.
in involuntary cases.

Here we leave you a detailed link with a video that describes what we tell you:

https://imgur.com/a/3roywbA

2022-11-05 20:52 UTC, ignacioaristo approved these changes

2022-11-05 21:50 UTC, julianpiaggio approved these changes
🕵️‍♂️ QA FEEDBACK

EMPLOYEE

First of all, we wanted to tell you that we consider that your pr complies
the requirements to be approved, and that you can merge to the master branch 👍

Now, if we consider leaving you some comments:

in the create action, the name field does not support putting spaces. This should be possible, since it may be the case that you need to write two names, for example (juan pablo)

in the create action, the last name field does not support putting spaces. This should be possible, since it may be the case that you need to write two names, for example (van vasten)

2022-11-05 21:50 UTC, merged