BaSP-TG-106: Employee - Profile Page
BaSP-a2022/ayom-a-trackgenix-app pull request #44
Opened 2022-11-22 18:04 UTC by CristianBucci

- Add form to edit employee's data
- Add 'Save changes' data, to update the data
- Add 'Change password' button (no functionality)
- Add 'Delete account' button (no functionality)
- Add Profile image

QA: 
How to test?:
- The profile page must show the employee's info: profile picture, name, email, address and phone. (All data has to be loaded on the inputs)
- The 'Save changes' button must update the data of the employee correctly
- The 'Change password' and 'Delete account' buttons won't have a functionality associated.

2022-11-22 20:33 UTC, matescarabino requested changes
I would also change the color of the "save changes" button, since it is the main one of this form and it does not stand out. But this is an UX / UI thing

2022-11-22 20:33 UTC, matescarabino commented on src/Components/Employees/Profile/index.js
> +            <Buttons type="submit" variant="primary" name="Save channges" />
Typo
```suggestion
            <Buttons type="submit" variant="primary" name="Save changes" />
```

2022-11-22 23:18 UTC, matescarabino approved these changes
LGTM

2022-11-22 23:30 UTC, Ansitox approved these changes
Everything look great, GJ

2022-11-22 23:45 UTC, MaxiG-dev approved these changes
Looks good for me! ✅

2022-11-23 11:58 UTC, NicoSan02 approved these changes

2022-11-23 11:59 UTC, merged