BaSP-TG-104: Projects page
BaSP-a2022/ayom-a-trackgenix-app pull request #45
Opened 2022-11-22 20:17 UTC by Ansitox

Add table with projects filtered by the employee's Id
Add 'Add hours'  button linked to the timesheets form

QA:
How to test?:

The home page must show the list of projects associated to the current employee (in this PR we used the ID of the employee called DONOT DELETE)
The  'Add hours' button must redirect you to the timesheets form

2022-11-22 20:43 UTC, matescarabino requested changes
Fix the typo. Everything else looks and works fine!

2022-11-22 20:43 UTC, matescarabino commented on src/Components/Employees/Home/index.js
> +    'Desription',
Fix typo

```suggestion
    'Description',
```

2022-11-22 22:34 UTC, matescarabino approved these changes

2022-11-22 23:23 UTC, renzopimentel approved these changes

2022-11-22 23:32 UTC, CristianBucci approved these changes
Everything looks fine!

2022-11-22 23:42 UTC, MaxiG-dev approved these changes
Looks good for me! ✅

2022-11-23 00:40 UTC, melissabonillasellanes approved these changes
Everything looks fine!

2022-11-23 02:05 UTC, NicoSan02 approved these changes

2022-11-23 02:05 UTC, merged