BaSP-TG-96: Implement React Lazy and Suspense
BaSP-a2022/ayom-a-trackgenix-app pull request #46
Opened 2022-11-22 22:53 UTC by Ansitox

- Install React Lazy
- Aplly react lazy and suspense

QA:
The navigation between the employees screens should work as they were doing it.

2022-11-22 23:23 UTC, renzopimentel approved these changes
Everything looks fine

2022-11-22 23:42 UTC, MaxiG-dev approved these changes
Looks good for me! ✅

2022-11-23 00:41 UTC, melissabonillasellanes approved these changes
Everything looks fine!

2022-11-23 03:26 UTC, matescarabino requested changes

2022-11-23 03:26 UTC, matescarabino commented on src/routes/employees.js
> +      <Route path="/employees/profile" component={EmployeeProfile} />
add this line in between

```suggestion
      <Route path="/employees/timesheets/:id" component={EmployeeProfile} />
```

2022-11-23 15:54 UTC, matescarabino approved these changes
LGTM

2022-11-23 18:40 UTC, NicoSan02 approved these changes

2022-11-23 18:40 UTC, merged