BaSP-TG-46: task
BaSP-a2022/ayom-a-trackgenix-app pull request #5
Opened 2022-11-02 02:11 UTC by MaxiG-dev

-Retrieve the data from the data base and list all the tasks.
-Create a list view where each item has a button to update and delete.
-Create methods to delete, update and add task.

2022-11-02 13:11 UTC, matescarabino approved these changes
I don't see anything wrong

2022-11-02 14:30 UTC, nicolasblasco requested changes

2022-11-02 14:30 UTC, nicolasblasco commented on src/Components/Tasks/TaskList/List.js
> +const form = () => {
Name should be more specific

2022-11-02 14:30 UTC, nicolasblasco commented on src/Components/Tasks/index.js
> +      setTasksList(data.data);
What happens if the request fails? We should handle the errors

2022-11-02 14:30 UTC, nicolasblasco commented on src/Components/Tasks/index.js
> +    setTasksList([...tasksList.filter((task) => task._id !== id)]);
What happens if the request fails? The del function doesn't break out of the deleteTask and the setTaskList removes the task. We should handle this situation

2022-11-02 14:30 UTC, nicolasblasco commented on src/Components/Tasks/Form/Form.js
> +    window.location.assign('/tasks');
What happens if the request fails? The put and post functions don't break out of the function and if there is an error it still navigates to the list view.

2022-11-02 14:42 UTC, nicolasblasco commented on src/Components/Tasks/index.js
> +      return error;
We could save the error inside a local state, and next show that error.

2022-11-02 16:09 UTC, CristianBucci commented
I don't see anything else to fix besides the comments already made!

2022-11-02 18:43 UTC, MaxiG-dev commented on src/Components/Tasks/index.js
> +    setTasksList([...tasksList.filter((task) => task._id !== id)]);
Done!

2022-11-02 18:43 UTC, MaxiG-dev commented on src/Components/Tasks/Form/Form.js
> +    window.location.assign('/tasks');
Done!

2022-11-02 18:55 UTC, MaxiG-dev commented on src/Components/Tasks/index.js
> +      return error;
Done!

2022-11-03 02:25 UTC, renzopimentel commented on src/Components/Tasks/index.js
> +    (await del(id)) ? setTasksList([...tasksList.filter((task) => task._id !== id)]) : '';
What happens it the request fails? We should handle the error situation so it won't change our task state.

2022-11-03 02:25 UTC, renzopimentel commented on src/Components/Tasks/tasks.module.css
> +.title {
Separation between the classes, just for better looking

2022-11-03 04:42 UTC, MaxiG-dev commented on src/Components/Tasks/index.js
> +    (await del(id)) ? setTasksList([...tasksList.filter((task) => task._id !== id)]) : '';
If the request fails the `(await del(id))` method returns false, so the task status is not update because this code is not executed.

2022-11-03 12:35 UTC, MaxiG-dev commented on src/Components/Tasks/tasks.module.css
> +.title {
Done!

2022-11-04 17:32 UTC, NicoSan02 approved these changes
🕵️‍♂️ **QA FEEDBACK**

**TASK**

First of all, we wanted to let you know that we consider that **your PR complies
the requirements to be approved**, and that you can merge to the master branch 👍

however we consider leaving you some comments:
*the design implemented for the action of creating a task looks a bit confusing regarding
 to the chosen colors and position. Some recommended options to make it look better would be:
	* put a border to the button, giving it independence and better visibility.
	* change font type, allowing it to be highlighted


![error task1](https://user-images.githubusercontent.com/107139347/200038000-725a9d67-0d54-4140-b4c9-e2698c3882f5.png)

* regarding the update response message, the message includes the task id, being
irrelevant in the answer itself and having no utility.


![error task2](https://user-images.githubusercontent.com/107139347/200038169-0bec8ba1-d047-44ac-ba2e-a679b8f4dc4c.png)


* when deleting a task, we notice that there is no question that validates the action, it simply throws a message that the task is done. A possible solution would be to add a query before, with the following text: ¿are you sure you want to delete the task?.

The following link illustrates the previous point:
[https://imgur.com/a/JpQMdkT](url)

2022-11-04 18:27 UTC, merged