BaSP-TG-126: Unify Code Redux
BaSP-a2022/ayom-a-trackgenix-app pull request #56
Opened 2022-12-09 03:33 UTC by matescarabino

- Unify redux constants names
- Unify redux actions
- Unify redux  reducers
- Unify redux thunks
- Fix all broken files
- Add new "shared" file to redux, modals are now stored there.

QA:
How to test?
I will add this after consulting with my teammates

2022-12-09 17:22 UTC, Ansitox approved these changes
Looks great to me, nicely done!

2022-12-09 17:22 UTC, Ansitox commented on src/redux/employees/reducer.js
> +          content: `Employee Successfully CREATED`
Change the backticks

2022-12-09 17:22 UTC, Ansitox commented on src/redux/employees/reducer.js
> +          content: `Employee Successfully UPDATED`
Change the backticks

2022-12-09 17:22 UTC, Ansitox commented on src/redux/projects/reducer.js
> +          content: `Project Successfully UPDATED`
Change the backticks

2022-12-09 17:22 UTC, Ansitox commented on src/redux/super-admins/reducer.js
>            content: `Could not CREATE SuperAdmin`
Change the backticks

2022-12-09 17:22 UTC, Ansitox commented on src/redux/super-admins/reducer.js
>            content: `Could not DELETE SuperAdmin`
Change the backticks

2022-12-09 17:22 UTC, Ansitox commented on src/redux/tasks/reducer.js
> +          content: `Task Successfully CREATED`
Change the backticks

2022-12-09 17:22 UTC, Ansitox commented on src/redux/tasks/reducer.js
> +          content: `Task Successfully UPDATED`
Change the backticks

2022-12-09 17:22 UTC, Ansitox commented on src/redux/timesheets/reducer.js
> +          content: `TimeSheet Successfully CREATED`
Change the backticks

2022-12-09 17:22 UTC, Ansitox commented on src/redux/timesheets/reducer.js
> +          content: `TimeSheet Successfully UPDATED`
Change the backticks

2022-12-10 01:37 UTC, CristianBucci submitted a review, later dismissed
Everything looks right!

2022-12-11 17:18 UTC, CristianBucci requested changes
Buttons don't work

2022-12-21 14:24 UTC, closed without merging