BaSP-TG-44: Projec entity
BaSP-a2022/ayom-a-trackgenix-app pull request #6
Opened 2022-11-02 02:31 UTC by CristianBucci

Add form in project, and create edit and delete project.

2022-11-02 13:08 UTC, matescarabino requested changes

2022-11-02 13:08 UTC, matescarabino commented on src/Components/Projects/Form/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/projects`, {
What happens if there is an error? I suggest you add a try-catch

2022-11-02 13:08 UTC, matescarabino commented on src/Components/Projects/Form/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/projects/${id}`, {
What happens if there is an error? I suggest you add a try-catch

2022-11-02 15:11 UTC, CristianBucci commented on src/Components/Projects/Form/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/projects`, {
Fixed!

2022-11-02 15:11 UTC, CristianBucci commented on src/Components/Projects/Form/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/projects/${id}`, {
Fixed

2022-11-02 15:11 UTC, CristianBucci commented on src/Components/Projects/listItems/index.js
> +  console.log(employeeData.filter((emp) => projectsEmployee.includes(emp._id)));
Fixed!

2022-11-02 15:44 UTC, matescarabino approved these changes

2022-11-02 17:19 UTC, nicolasblasco requested changes

2022-11-02 17:19 UTC, nicolasblasco commented on src/Components/Projects/index.js
>  function Projects() {
We should use an arrow function

2022-11-02 17:19 UTC, nicolasblasco commented on src/Components/Projects/index.js
> +import ProjectTable from './List';
We have to be consistent with the team and call this component ProjectList

2022-11-02 17:19 UTC, nicolasblasco commented on src/Components/Projects/Form/index.js
> +      alert('Project Created');
When a project is created we should navigate back to the projects list

2022-11-02 17:19 UTC, nicolasblasco commented on src/Components/Projects/Form/index.js
> +      alert('Project Updated');
When a project is updated we should navigate back to the projects list

2022-11-02 17:26 UTC, nicolasblasco commented on src/Components/Projects/listItems/index.js
> +    .join(',');
With resolving the ticket TG-57 from our backend there is no need to do this because the date will be populated correctly. Resolve this issue first and then remove this code.

2022-11-03 04:54 UTC, CristianBucci commented on src/Components/Projects/index.js
> +  };
fixed!

2022-11-03 04:54 UTC, CristianBucci commented on src/Components/Projects/index.js
> +      alert('Could not GET Project.', error);
Fixed!

2022-11-03 04:54 UTC, CristianBucci commented on src/Components/Projects/listItems/index.js
> +import { useEffect, useState } from 'react';
Fixed!

2022-11-03 04:54 UTC, CristianBucci commented on src/Components/Projects/index.js
>  function Projects() {
Fixed!

2022-11-03 04:54 UTC, CristianBucci commented on src/Components/Projects/index.js
> +import ProjectTable from './List';
Fixed!

2022-11-03 04:55 UTC, CristianBucci commented on src/Components/Projects/Form/index.js
> +      alert('Project Created');
Fixed!

2022-11-03 04:55 UTC, CristianBucci commented on src/Components/Projects/Form/index.js
> +      alert('Project Updated');
Fixed!

2022-11-03 04:55 UTC, CristianBucci commented on src/Components/Projects/listItems/index.js
> +    .join(',');
Resolved!

2022-11-03 12:15 UTC, nicolasblasco commented on src/Components/Projects/index.js
> +      setProjects('Cannot get projects', { error });
We shouldn't use the setProjects to set an error state. We should create a new state [error, setError] and manage the errors with this.

2022-11-03 12:21 UTC, ignacioaristo requested changes

2022-11-03 12:21 UTC, ignacioaristo commented on src/Components/Projects/Form/index.js
> +          employees: employees,
this is the same than this:
`employees,`
When both name are equals, we can do this.

2022-11-03 12:21 UTC, ignacioaristo commented on src/Components/Projects/Form/index.js
> +          employees: employees,
same here

2022-11-03 12:21 UTC, ignacioaristo commented on src/Components/Projects/listItems/index.js
> +  console.log(projectsEmployeesNames);
remove this console log.

2022-11-03 12:21 UTC, ignacioaristo commented on src/Components/Projects/listItems/index.js
> +    .map((e) => e.employeeId)
we need to be more specific with the name of the maps. Change `e` for something `employee`

2022-11-03 12:21 UTC, ignacioaristo commented on src/Components/Projects/listItems/index.js
> +    .map((n) => [n.name, ' ', n.lastName, ' ']);
Same here.

2022-11-03 14:00 UTC, CristianBucci commented on src/Components/Projects/index.js
> +      setProjects('Cannot get projects', { error });
Fixed!

2022-11-03 14:00 UTC, CristianBucci commented on src/Components/Projects/Form/index.js
> +          employees: employees,
Fixed!

2022-11-03 14:00 UTC, CristianBucci commented on src/Components/Projects/Form/index.js
> +          employees: employees,
Fixed!

2022-11-03 14:00 UTC, CristianBucci commented on src/Components/Projects/listItems/index.js
> +  console.log(projectsEmployeesNames);
Fixed!

2022-11-03 14:00 UTC, CristianBucci commented on src/Components/Projects/listItems/index.js
> +    .map((e) => e.employeeId)
Fixed!

2022-11-03 14:00 UTC, CristianBucci commented on src/Components/Projects/listItems/index.js
> +    .map((n) => [n.name, ' ', n.lastName, ' ']);
Fixed!

2022-11-03 14:59 UTC, nicolasblasco approved these changes

2022-11-04 05:41 UTC, renzopimentel commented on src/Components/Projects/Form/createItem.module.css
> +label{
label and button selectors should be shown above the first class

2022-11-04 05:41 UTC, renzopimentel commented on src/Components/Projects/Form/createItem.module.css
> +button{
Same as above

2022-11-04 11:21 UTC, CristianBucci commented on src/Components/Projects/Form/createItem.module.css
> +label{
Fixed!

2022-11-05 14:36 UTC, julianpiaggio approved these changes
🕵️‍♂️ QA FEEDBACK

PROJECTS

First of all, we wanted to tell you that we consider that your pr complies
the requirements to be approved, and that it can be merged into the master branch 👍

Now, if we consider leaving you some comments:

* in the create action, when leaving fields empty or with invalid data, it throws a banner with a message error , which only has one apparent way to close it, which is a button that takes you to the page major. This is not recommended, as you should be able to continue with the form.

Here is a link with a video so you can reproduce this error:
https://imgur.com/a/81RsLJo

* Regarding the previous point, we found a close button on the right side of the modal, but not
is detailed or visible to the naked eye. When you close it that way, all the fields are left blank.
We advise you to see the close button on one side. Likewise, when putting an erroneous field you must not reset all, but you have the possibility to modify that same field.


![errror projects close](https://user-images.githubusercontent.com/84697592/200124324-c709cf37-d1b5-4059-9d89-f887689f76f4.png)


* in the create action, the name field allows you to enter only spaces, only numbers, and only characters.
 What we consider necessary would be to be able to add a validation that yes or yes contains letters and that these can be accompanied by other characters.

![error projects datos inputs](https://user-images.githubusercontent.com/84697592/200124501-1cc635e1-7f46-440a-bc8e-52aff824c2d4.png)


* in the startDate field it allows to put numbers very far from the current one (eg: 01/01/0001). what is advisable it would be to put a minimum value so that it can be considered correct.

![error projects fecha](https://user-images.githubusercontent.com/84697592/200124586-0b306818-41e4-4aef-87f5-05091d6dc038.png)


* in the field endDate it allows to put more than four numbers in the year. what is advisable
It would be to put a limit value so that it can be considered correct.

![error projects fecha](https://user-images.githubusercontent.com/84697592/200124586-0b306818-41e4-4aef-87f5-05091d6dc038.png)

* when putting add employee and not passing valid data throws a very technical error. Could you give an answer simpler, for example, "this field cannot be left empty"

![error projects cartel employee vacio](https://user-images.githubusercontent.com/84697592/200124688-b1ebed7b-ffe0-4927-b059-3698eb01b25b.png)


* in the employee rate field, accept negative numbers, 0, and no data. The expected would be values ​​greater than 0

* Allows you to confirm the creation of projects with a start date greater than the closing date. This is inconsistent and so one solution would be for the start date to always be less than the end date.

![error projects endDate](https://user-images.githubusercontent.com/84697592/200124935-78cdceb0-f73b-4435-8375-4dada90a6545.png)


* when wanting to cancel the create action, the button that fulfills said function takes us to a page with the following legend "localhost refused connection"

Here is a link with a video so you can reproduce this error:
https://imgur.com/a/cfzEtXQ

* the delete action does not provide a confirmation message to complete it. This confirmation is recommended in involuntary cases.

* the edition success message returns a message with the id data, this being unnecessary.

2022-11-05 14:48 UTC, ignacioaristo approved these changes

2022-11-05 14:48 UTC, merged