BaSP-TG-142: Super Admin Home
BaSP-a2022/ayom-a-trackgenix-app pull request #64
Opened 2022-12-17 18:48 UTC by Ansitox

- In Home add admins Table
- Create Admins only button
- Edit Admins only button
- Add search shared component
- Delete Admin button and functionality (soft delete)
- When click create admin button in the table, redirect to create Admin form
- When click edit admin button in the table, redirect to edit Admin form

QA:
How to test?:
Log in as a Super Admin (email: oclacep@wikimedia.org, password: prueba1234)
When logged you should se a nav bar (temporary)
In the Home page you should see a list of Admins
The "+" button redirects you to a form page (empty)
The "edit" buttons should redirect you to the same form, but the path should have the id of the admin to edit.
The "delete" button should open a modal, on cancel modal will close, on confirm a message modal will appear with the error/success message, then will close.
Note: The anv bar is temporaryand just to use on the test of the PRs, any bad function on navigation should be ignored.

2022-12-17 23:20 UTC, matescarabino requested changes

2022-12-17 23:20 UTC, matescarabino commented on src/Components/SuperAdmins/Home/index.js
> +      console.log(itemId);
Is this necessary?

2022-12-18 13:14 UTC, CristianBucci approved these changes
Everything looks right!

2022-12-19 12:41 UTC, matescarabino approved these changes
LGTM

2022-12-19 16:58 UTC, julianpiaggio approved these changes
🕵️‍♂️ QA FEEDBACK

We wanted to tell you that we consider that your pr complies
the requirements to be approved, and that it can be merged into the master branch 👍

2022-12-19 16:58 UTC, merged